### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/practica-de-mockup-y-front-end-remi#2]
[Práctica 3 - Diseño de Mockup.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-mockup-y-front-end-remi/files/8367882/Practica.3.-.Diseno.de.Mockup.pdf)

**Comment by DuilioAquino10** [comment]
CALIFICACIÓN: 20/20.

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/163262648-1dfc65d1-da6c-44c2-960a-8189f5ca84a8.png)
El inicio de sesion para una Dapp debe ser por medio de Near para una mayor seguridad...

**Comment by josealfredo79** [comment]
No es necesario utilizar facebok o google para iniciar sesion 
![image](https://user-images.githubusercontent.com/58342642/163263101-6e28ebed-1e03-43bb-9c02-3028248b2a6c.png)
Se debe utilizar near y ademas en este semestre no vamos a programar front-end solo el backend

**Comment by josealfredo79** [comment]
Realizar los cambios para tomar en cuenta la practica

**Comment by Band-hi** [comment]
No hay necesidad, nuestro equipo había decidido decantarse por la tecnología 2.0 tal como lo indicamos en un documento que usted solicitó.
![image](https://user-images.githubusercontent.com/46431649/164273365-83402a8d-bf9c-4b68-8d99-a7044e652df3.png)

> ![image](https://user-images.githubusercontent.com/46431649/164273501-15721685-5707-4a85-b93d-90d2fa87b785.png)

**Comment by josealfredo79** [comment]
Si esta bien la tecnología, solo expongo lo siguiente:
Los talleres que se explicaran en clase son con tecnología Web 3.0, se
explicara como compilar y desplegar un contrato inteligente,como realizar
operaciones de lectura y escritura en un contrato inteligente, se
realizaran llamadas de una api con el contrato inteligente, y la mayoria de
las prácticas son utilizando contratos inteligentes. En clase no explicare
como funciona una app cliente servidor.
Por su atencion a la presente gracias.

**Comment by josealfredo79** [comment]
Te mando parte del taller y clases donde expondremos cómo se compila un
contrato inteligente con tecnología Web 3.0, y tambien para que cheques en
el Moodle las prácticas estan orientadas para contratos inteligentes.
Estamos disponibles para cualquier consulta.

Por su atención a la presente gracias. Lo bueno es que todavia NO empezamos
a programar, regresando empezamos a programar contratos inteligentes, solo
se desarrollará el contrato donde solo almacenaremos información.

Taller de Contratos inteligentes - Presentaciones de Google
<https://docs.google.com/presentation/d/1CRjEmJI5Wshs2MRRzUqK7EE0EVeZNKkRX5ZuP6_H5QU/edit#slide=id.p>
Taller de Contratos Inteligentes Escritura y lectura ejercicio 2 -
Presentaciones de Google
<https://docs.google.com/presentation/d/1sq9uQxcToEoJb_BhYX-VnmTcezhLs16KlRvwCkGwPZg/edit#slide=id.p>

**Comment by IsaHuerta23** [comment]
Todo perfecto pero entonces por qué al principio del Sprint nos permitió elegir trabajar en la web 2.0 o web 3.0 si después terminó imponiéndonos la web 3.0. 
Si ese era el caso nos lo hubiera dicho desde un principio y hubiéramos orientado nuestro proyecto a esa web y así evitar este tipo de malentendidos.

**Comment by Rmz-Rigo** [comment]
Concuerdo con mis compañeros del proyecto, en nuestro caso estamos interesados en trabajar con la web 2.0, ya que es sobre la cual tenemos más conocimiento, sin embargo usted nos está obligando a enfocar nuestro proyecto (en la web 3.0), cuando usted claramente al principio nos dio dos opciones: elegir la web 2.0 ó 3.0.

**Comment by josealfredo79** [comment]
Si no hay problema...solo expongo lo que se va hacer en clases....

**Comment by IsaHuerta23** [comment]
Aquí está el trabajo con las correcciones pertinentes.

[Práctica 3 - Diseño de Mockup CORREGIDO.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-mockup-y-front-end-remi/files/8534298/Practica.3.-.Diseno.de.Mockup.CORREGIDO.pdf)
